
resources:
  repositories:
  - repository: templates
    type: git
    name: CustomizedOpenWRT/pipelines-templates

jobs:
- job:
  displayName: Build for
  pool:
    vmImage: Ubuntu-Latest
  strategy:
    matrix:
      ath79:
        BuildTarget: ath79
        BuildSubtarget: generic
      ipq806x:
        BuildTarget: ipq806x
        BuildSubtarget: generic
      x86_64:
        BuildTarget: x86
        BuildSubtarget: '64'
    maxParallel: 3
  timeoutInMinutes: 0
  steps:
  - template: steps/install-dependencies.yml@templates

  - template: steps/download-online-artifacts.yml@templates
    parameters:
      target: $(BuildTarget)
      subtarget: $(BuildSubtarget)
      patterns: '*(sdk)*\.tar\.xz'

  - template: steps/sdk-steps.yml@templates
    parameters:
      customFeeds: src-link this $(Build.SourcesDirectory)
      packages: -a -p this

  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      artifactName: Packages
      pathtoPublish: $(Build.SDKRepoPath)/this
