#!/bin/sh
#
# Copyright (C) 2019 expiron <expiron18@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

. /lib/functions.sh
. /lib/functions/procd.sh > /dev/null 2>&1

bin="/usr/bin/tsauth"
self="$1"
run="$2"
[ -n "$run" ] || run=0

keep_online() {
	local cfg="$1"
	local account
	[ -x "$bin" ] || return

	eval "$("validate_online_options" "$cfg" validate_mklocal)"
	"validate_online_options" "$cfg" || return
	[ "$disabled" = 0 ] || return

	[ -n "$account" ] || return
	eval "$(validate_account_options "$account" validate_mklocal)"
	validate_account_options "$account" || return
	[ "$disabled" = 0 ] || return

	options="-u $username -p $password"
	[ "$target" = "self" ] && {
		[ "$ipv4" = 0 ] || [ "$(curl -sI -m 1 -o /dev/null -w '%{http_code}' info.tsinghua.edu.cn)" -ne 200 ] || ipv4=0
		[ "$ipv6" = 0 ] || [ "$(curl -sI -m 1 -o /dev/null -w '%{http_code}' bt.byr.cn)" -ne 301 ] || ipv6=0
	}
	[ "$ipv4" = 0 ] && [ "$ipv6" = 0 ] && return
	[ -z "$self" ] || [ "$target" = "$self" ] || return
	[ "$target" = "self" ] || options="$options -d $target"
	[ "$inside" = 0 ] || options="$options --inside"
	[ "$ipv4" = 0 ] || options="$options --ipv4"
	[ "$ipv6" = 0 ] || options="$options --ipv6"

	echo "$options" | xargs "$bin"
	[ "$target" = "self" ] && {
		: $((run += 1))
		[ "$run" -gt 3 ] || sh -c "sleep ${run}m; tsauth-keep-online self $run" &
	}
}

validate_mklocal() {
	local tuple opts

	shift 2
	for tuple in "$@"; do
		opts="${tuple%%:*} $opts"
	done
	[ -z "$opts" ] || echo "local $opts"
}

validate() {
	uci_validate_section tsauth "$@"
}

validate_account_options() {
	local cfg="$1"; shift
	local func="$1"; shift

	"${func:-validate}" account "$cfg" "$@" \
		'disabled:bool:0' \
		'username:string' \
		'password:string'
}

validate_online_options() {
	local cfg="$1"; shift
	local func="$1"; shift

	"${func:-validate}" online "$cfg" "$@" \
		'disabled:bool:0' \
		'account:uci("tsauth", "@account")' \
		'target:ipaddr:self' \
		'inside:bool:0' \
		'ipv4:bool:1' \
		'ipv6:bool:1'
}

config_load tsauth
config_foreach keep_online online
